name: Max_store
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.20.2
  lottie: ^3.1.0 # OR RIVE
  shimmer: ^3.0.0
  logger: ^2.2.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.0
  url_launcher: ^6.2.6
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.1.0
  wakelock_plus: ^1.2.3 #Only being used in the Dummy Data Uploader to keep screen on.
  package_info_plus: ^8.1.1
  email_otp: ^3.0.2
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  flutter_multi_formatter: ^2.0.0
  country_code_picker: ^3.2.0


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  share_plus: ^10.0.0

  # Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  google_sign_in: ^6.2.1
  coupon_uikit: ^0.2.1
  flutter_local_notifications: ^18.0.0
  firebase_messaging: ^15.2.1
  country_code_text_field: ^1.1.2
  firebase_analytics: ^11.4.1

  # Payment
  flutter_paypal: ^0.2.1

  #--------------- ./ PACKAGES END ------------------#

  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/images/support_preson/
    - assets/flags/
    - assets/images/whatsapp/
    - assets/logos/max-Store-splash-logo.png

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/max-Store-splash-logo_copie2.png
  image_dark: assets/logos/max-Store-splash-logo_copie2.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/max-Store-splash-logo_copie2.png
    image_dark: assets/logos/max-Store-splash-logo_copie2.png

  web: false
