// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATHyGmeU6_TRN3rrbRVck1_soIQjv6tDY',
    appId: '1:177186596379:web:2d99c92e27bc34ea573abe',
    messagingSenderId: '177186596379',
    projectId: 'sos1-5421b',
    authDomain: 'sos1-5421b.firebaseapp.com',
    storageBucket: 'sos1-5421b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtnS3ub03JNUdwemrkGlfHZ8Uon3jsYI',
    appId: '1:177186596379:android:d06b1696bdb9f4fd573abe',
    messagingSenderId: '177186596379',
    projectId: 'sos1-5421b',
    storageBucket: 'sos1-5421b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6-SEwGniCd5o6esxxRphz0nrHTjtii6M',
    appId: '1:177186596379:ios:8ed5ab0f45e4b951573abe',
    messagingSenderId: '177186596379',
    projectId: 'sos1-5421b',
    storageBucket: 'sos1-5421b.appspot.com',
    androidClientId: '177186596379-apaj6bdt4mjhuf7ijqkaiuvafl84obm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6-SEwGniCd5o6esxxRphz0nrHTjtii6M',
    appId: '1:177186596379:ios:8ed5ab0f45e4b951573abe',
    messagingSenderId: '177186596379',
    projectId: 'sos1-5421b',
    storageBucket: 'sos1-5421b.appspot.com',
    androidClientId: '177186596379-apaj6bdt4mjhuf7ijqkaiuvafl84obm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATHyGmeU6_TRN3rrbRVck1_soIQjv6tDY',
    appId: '1:177186596379:web:6b8860a1bc66d986573abe',
    messagingSenderId: '177186596379',
    projectId: 'sos1-5421b',
    authDomain: 'sos1-5421b.firebaseapp.com',
    storageBucket: 'sos1-5421b.appspot.com',
  );

}